### ISSUE TITLE
[1.12] Repair effect downgrades Thermal Expansion satchels and flux capacitors

### ISSUE THREAD

**Issue by CplPibald** [Tmtravlr/PotionCore#3]
Using Thermal Expansion, drink a potion of Repair.

Satchels and flux capacitors from Thermal Expansion use metadata 0-4 to determine upgrade level.   The Repair effect reduces this number to meta 0, which is the most basic version, removing all upgrades and destroying any items/power over the basic capacity.

**Comment by Tmtravlr** [comment]
That's fixed in the latest version
